# Generated by Django 3.2.6 on 2021-08-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date_soumise', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('date_soumise',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('MAPL', 'Apllicant principale'), ('JAPL', 'Apllicant conjoint'), ('COAP1', 'Co-Apllicant1'), ('COAP2', 'Co-Applicant2')], default='MAPL', max_length=5, verbose_name='Type: ')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom: ')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom: ')),
                ('no_civique', models.CharField(max_length=20, verbose_name='Numéro civique: ')),
                ('addresse_civique', models.CharField(max_length=100, verbose_name='Adresse: ')),
                ('code_postale', models.CharField(max_length=7, verbose_name='Code postale: ')),
                ('province', models.CharField(choices=[('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Québec')], max_length=2, verbose_name='Province: ')),
                ('nas', models.IntegerField(verbose_name="Numéro d'assurance sociale: ")),
                ('date_de_naissance', models.DateField(verbose_name='Date de naissance: ')),
                ('employeur', models.CharField(max_length=100, verbose_name='Employeur: ')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salaire: ')),
                ('code_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.application')),
            ],
        ),
    ]
