# Generated by Django 3.2.6 on 2021-08-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date_soumise',)},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('code_demande', 'type_client')},
        ),
    ]
